### ISSUE TITLE
Update to 2.2.9

### ISSUE THREAD

**Issue by aparsons** [webjars/Semantic-UI#42]
Semantic UI has updated to 2.2.9. Please make a webjars release. Thank you!

https://github.com/Semantic-Org/Semantic-UI/releases/tag/2.2.9

**Comment by aparsons** [comment]
@jamesward I am not seeing a jar for 2.2.9 at https://mvnrepository.com/artifact/org.webjars/Semantic-UI

**Comment by jamesward** [comment]
It is on Maven Central: https://repo1.maven.org/maven2/org/webjars/Semantic-UI/

Maybe the mvnrepository has a sync delay.
