### ISSUE TITLE
Please Release Version: 2.5.0

### ISSUE THREAD

**Issue by DPritu** [webjars/Semantic-UI#49]
Could you please create a WebJar for Semantic-UI v2.5.0?

https://github.com/Semantic-Org/Semantic-UI/releases/tag/2.5.0

**Comment by jamesward** [comment]
I've moved this to be user-deployable via https://webjars.org
https://github.com/webjars/webjars-classic/blob/main/Semantic-UI.properties

I'm releasing `2.5.0` and then we will see if it all worked shortly.

**Comment by jamesward** [comment]
This has been deployed and looks right to me. Let me know if there are any issues.

**Comment by DPritu** [comment]
Thank you! I can confirm that everything works as expected for me.
